In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,4])
print(arr)

[1 2 3 4 4]


In [5]:
# vector
vector = np.array([1,34,5,6,2,1])
print(vector, vector.shape)

[ 1 34  5  6  2  1] (6,)


In [6]:
# matrix
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(matrix, matrix.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [9]:
# its like range in python
np.arange(10)
np.arange(2,10)
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [10]:
# for making all zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
# for making all ones
# 1d
np.ones(4)
# 2d
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# random decimal numbers
np.random.random(5)

# 2d
np.random.random((5,5))
np.random.randint(1,100, (3,4)) #mean k 1 - 100 tk k bech me random values and 3 x 4 ki matrix honi chahei

array([[26, 18,  7, 75],
       [77, 31, 68, 53],
       [80, 92, 95, 68]])

In [18]:
# very common in plotting
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
# create an identity matrix
arr = np.identity(5) # 5 x 5

In [23]:
# array attributes
# ndim
arr.ndim #means k ye 2d ha if it return 2

2

In [24]:
# shape
arr.shape

(5, 5)

In [25]:
# size 5 x 5 = 25
arr.size

25

In [26]:
# dtype - datatype
arr.dtype

dtype('float64')

In [27]:
# item size
arr.itemsize #means each element uses 8 bytes

8

In [31]:
# change data type using astype
arr = arr.astype(int)
arr.dtype

dtype('int64')

In [33]:
# reshape
arr = np.arange(12)
print(arr)
print(arr.shape)
arr = arr.reshape(3,4)
print(arr, arr.shape)
# but ye 12 divisible ha isi leye, 3 X 4 = 12


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [34]:
# use -1 and numpy can calc the other dimension its self
arr.reshape(3,-1)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
# array operations
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
arr1 = arr1 + 5
print(arr1)

# subtraction
arr1 = arr1 - 10
print(arr1)

# multiplication
arr1 = arr1 * 2
print(arr1)

# division
arr1 = arr1 / 10
print(arr1)

# power
arr1 = arr1 ** 2
print(arr1)

# modulus
arr1 = arr1 % 2
print(arr1)

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]
[-4 -3 -2 -1  0  1]
[-8 -6 -4 -2  0  2]
[-0.8 -0.6 -0.4 -0.2  0.   0.2]
[0.64 0.36 0.16 0.04 0.   0.04]
[0.64 0.36 0.16 0.04 0.   0.04]


In [46]:
# comparision operations
arr = np.arange(0,15)
arr > 5

arr < 10

arr == 8 #jon sa el ho ga wo true dikae ga array me

arr != 5

arr >= 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [47]:
mask1 = arr > 5
print(arr[mask1])

[ 6  7  8  9 10 11 12 13 14]


In [52]:
# vector operations
a = np.arange(1,10)
b = np.arange(10,19)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 13 15 17 19 21 23 25 27]
[-9 -9 -9 -9 -9 -9 -9 -9 -9]
[ 10  22  36  52  70  90 112 136 162]
[0.1        0.18181818 0.25       0.30769231 0.35714286 0.4
 0.4375     0.47058824 0.5       ]


In [55]:
# mathematical functions
arr = np.array([2,5,7,10])
print(arr.min())
print(arr.max())
print(arr.sum())
print(arr.prod())


2
10
24
700


In [59]:
# statistical functions
arr.mean() #average
# median middle value after sorting
np.median(arr)

# standard deviation
arr.std()
# variance
arr.var()

np.float64(8.5)

In [65]:
# trignometric functions
angles = np.array([0, np.pi/2, np.pi])
np.sin(angles)
np.cos(angles)
np.tan(angles)
np.deg2rad(90)

np.float64(1.5707963267948966)

In [66]:
# dot product

np.dot(a,b)

np.int64(690)

In [68]:
# logarithms & exponentials
np.log(arr)
print(np.log10(arr))
print(np.exp(arr)) #e ^ x


[0.30103    0.69897    0.84509804 1.        ]
[7.38905610e+00 1.48413159e+02 1.09663316e+03 2.20264658e+04]


In [70]:
# rounding function
np.round(arr)
print(np.floor(arr))
print(np.ceil(arr))

[ 2.  5.  7. 10.]
[ 2.  5.  7. 10.]


In [73]:
# indexing
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[4])
print(arr[-1])
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr[1,2])

10
30
50
50
6


In [76]:
# slicing
arr[1:4]
arr[0, 0::2]

array([1, 3])

In [ ]:
# iterating
for num in arr:
  print(num)

In [77]:
for value in np.nditer(arr):
  print(value)
  # np.nditer() is useful for iterating through arrays of any dimension.


1
2
3
4
5
6


In [79]:
# stacking
a = np.arange(1,10)
b = np.arange(10, 19)

# horizontal stacking
hs =np.hstack((a,b))
print(hs)
vs = np.vstack((a,b))
print(vs)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [81]:
# splitting
arr = np.array([1,2,3,4,5,6])
np.hsplit(arr,3)
matrix = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

np.vsplit(matrix,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]