In [1]:
import numpy as np

In [30]:
arr = np.random.randint(1, 100, 10)
print(arr)

print("Sort: ",np.sort(arr))

arr2d = np.random.randint(1, 100, (3,3))
print("2d array:",arr2d)
print("2d Array sorted:",np.sort(arr2d)

      )

[69 31  1 13  5  3  4 77 91 24]
Sort:  [ 1  3  4  5 13 24 31 69 77 91]
2d array: [[89 10 19]
 [98 22 25]
 [30  9 59]]
2d Array sorted: [[10 19 89]
 [22 25 98]
 [ 9 30 59]]


In [9]:
# np append
np.append(arr, 3) #end me 3

array([82, 23, 57, 29, 44, 85, 91, 72,  7, 40,  3])

In [10]:
np.append(arr, [3,4,5,24,4])

array([82, 23, 57, 29, 44, 85, 91, 72,  7, 40,  3,  4,  5, 24,  4])

In [12]:
np.append(arr2d, [[5,5,5]], axis=0)
# add kar de ga aik new row in the end
# axis 0 - row and 1 - col


array([[ 9, 21, 86],
       [94, 77, 51],
       [22, 17, 88],
       [ 5,  5,  5]])

In [14]:
arr2 = np.arange(1,10)
np.concatenate((arr,arr2))

np.concatenate((arr, arr2), axis=0)

array([82, 23, 57, 29, 44, 85, 91, 72,  7, 40,  1,  2,  3,  4,  5,  6,  7,
        8,  9])

In [16]:
# np unique
np.unique(arr)

values, counts = np.unique(arr, return_counts= True)
print(values, counts)

[ 7 23 29 40 44 57 72 82 85 91] [1 1 1 1 1 1 1 1 1 1]


In [27]:
# np.expand_dims() add a new dimension
arr3 = np.array([1,2,3])
arr3.shape

# convert it to a row vector
arr3 = np.expand_dims(arr3, axis=0)
arr3.shape

# convert into a col vector
arr3 = np.array([1,2,3])
np.expand_dims(arr3, axis=1)

array([[1],
       [2],
       [3]])

In [28]:
# np where
arr4 = np.array([10,20,30,40])
np.where(arr > 20)

(array([2, 3]),)

In [31]:
# np.argmax()  returns the index of hte maximum value
np.argmax(arr)

np.int64(8)

In [35]:
# np.argmin()  returns the index of hte minimum value
np.argmin(arr)

np.argmin(arr2d, axis=0)

array([2, 2, 0])

In [36]:
# np.cumsum cumulative sum

np.cumsum(arr)

array([ 69, 100, 101, 114, 119, 122, 126, 203, 294, 318])

In [37]:
# cumprod
np.cumprod(arr)

array([          69,         2139,         2139,        27807,
             139035,       417105,      1668420,    128468340,
        11690618940, 280574854560])

In [39]:
# np.percentile() - Finds percentile values
np.percentile(arr, 50)
np.percentile(arr,25)
np.percentile(arr,75)

np.float64(59.5)

In [40]:
# np.histogram
hist, bins = np.histogram(arr, bins=5)
print(hist)
print(bins)

# Histogram counts tell you how many values fall into each interval.

# Very useful before plotting histograms.

[5 2 0 1 2]
[ 1. 19. 37. 55. 73. 91.]


In [42]:
# np.corrcoef()
# find correlation between variable
np.corrcoef(arr, arr)

# Values range from -1 to 1:

# 1 → perfect positive correlation
# 0 → no linear relationship
# -1 → perfect negative correlation


array([[1., 1.],
       [1., 1.]])

In [43]:
# np.isin()
# cheks membership
np.isin(arr, [2,5])

array([False, False, False, False,  True, False, False, False, False,
       False])

In [44]:
# np.flip
print(arr)
print(np.flip(arr))

[69 31  1 13  5  3  4 77 91 24]
[24 91 77  4  3  5 13  1 31 69]


In [45]:
# np.ptp
# peak to peak
# max - min
np.ptp(arr)

np.int64(90)

In [46]:
# np.delete
np.delete(arr, 2)

array([69, 31, 13,  5,  3,  4, 77, 91, 24])

In [48]:
# delete row
print(arr2d)
print(np.delete(arr2d, 1, axis=0))
print(arr2d)

[[89 10 19]
 [98 22 25]
 [30  9 59]]
[[89 10 19]
 [30  9 59]]
[[89 10 19]
 [98 22 25]
 [30  9 59]]


In [54]:
# set functions
# np.union1d()
np.union1d(arr, arr)
# np.intersect1d()
np.intersect1d(arr, arr2)
# np.setdiff1d()
np.setdiff1d(arr, arr2)
# np.setxor1d()
# Values that are unique to each array (not common).
np.setxor1d(arr, arr2)


array([ 2,  6,  7,  8,  9, 13, 24, 31, 69, 77, 91])

In [57]:
# swapaxes()
# Swaps two axes of an array.
arr4 = np.arange(24).reshape(2,3,4)
print(arr4)
arr4.swapaxes(0,1)
print(arr4)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [58]:
# np.random.uniform()
# generate random deimal numbers in a given range
np.random.uniform(0,1,5)

array([0.7309478 , 0.0302388 , 0.74772269, 0.34984493, 0.38383155])

In [59]:
#np.count_nonzero()
np.count_nonzero(arr)

10